typography_spectrum: 0.48315297113731503
color:
  brandStrength: 0.9988893438130617
  lightness: 0.04944273200817406
  saturation: 0.6505464939400554
  rhythmicContrast: 0.30773140164092183
  brandColors:
    - '#E1E6FA'
    - '#C4D7ED'
    - '#ABC8E2'
    - '#375D81'
    - '#183152'
layout_spectrum: 0.007406188175082207
author:
  name: Eric
  email: eric@PangaeaResources.net
  url: www.PangaeaResources.net
name: Welcome
navigation:
  - name: about
    url: www.PangaeaResources.net
    type: external
favicon: >-
  https://the-grid-user-content.s3-us-west-2.amazonaws.com/850b4c01-9d53-4d2e-ae3e-d457ad11736c.jpg
title: Pangaea Resources (Pty) Ltd
description: 'African Solutions with a global mindset '
